#> config.toml

[project]
name = "myproject"
description = "A new Rust project"
authors = ["Your Name <you@example.com>"]
version = "0.1.0"
edition = "2021"

[toolchain]
channel = "nightly-2023-02-22"
components = [ "rustfmt", "rustc-dev" ]
targets = [ "wasm32-unknown-unknown", ]
profile = "minimal"


[[ide.vscode]]
enable = true
languages = ["nix", "rust", "toml", "shellscript", "json"]
extensions = ["even-better-toml", "rust-analyzer", "nixfmt","rome"]
settings = []

[[ide.helix]]
enable = true
languages = ["nix", "rust", "toml", "shellscript"]
extensions = []
settings = []

[[ide.neovim]]
enable = false
extensions = []
settings = []

[[ide.emacs]]
enable = false
extensions = []
settings = []

[[crates.serde]]
version = "latest"
features = ["derive"]

[[crates.reqwest]]
version = "0.11.3"
features = ["json"]

[[crates.leptos]]
version = ""

[ignore]
path = "./gitignore"
directories = ["debug", "target", "tmp"]
files = ["*.log", "*.tmp", "*.bak"]
