[package]
name = "trust"
authors = ["Craig Cole <32288735+Craole@users.noreply.github.com>"]
edition = "2021"
description = "A rust project generated via Nix Flakes"
version = "0.1.0"

[dependencies]
clap = { version = "4.3.14", features = ["derive"] }
